add version checks, rework web loading, WIP docs

diff --git a/.github/workflows/sodium_libs_ci.yaml b/.github/workflows/sodium_libs_ci.yaml
--- a/.github/workflows/sodium_libs_ci.yaml
+++ b/.github/workflows/sodium_libs_ci.yaml
@@ -87,6 +87,10 @@ jobs:
       - name: install ChromeDriver (web)
         if: matrix.platform == 'web'
         uses: nanasess/setup-chromedriver@master
+      - name: fetch sodium.js (web)
+        if: matrix.platform == 'web'
+        run: flutter pub run sodium_libs:update_web
+        working-directory: packages/sodium_libs/example
       - name: install minisign (android)
         if: matrix.platform == 'android'
         run: |
@@ -132,67 +136,82 @@ jobs:
           --release
           --browser-name=${{ matrix.drive }}
         working-directory: packages/sodium_libs/example
-  # release:
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - test
-  #   if: github.ref == 'refs/heads/main'
-  #   outputs:
-  #     update: ${{ steps.version.outputs.update }}
-  #     tag_name: ${{ steps.version.outputs.tag_name }}
-  #   steps:
-  #     - uses: subosito/flutter-action@v1
-  #     - uses: actions/checkout@v2
-  #     - uses: Skycoder42/action-dart-release@v1
-  #       id: version
-  #       with:
-  #         src_dir: packages/${{ env.PACKAGE_NAME }}
-  #     - name: Create Release
-  #       if: steps.version.outputs.update == 'true'
-  #       uses: actions/create-release@v1
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       with:
-  #         tag_name: ${{ env.PACKAGE_NAME }}/v${{ steps.version.outputs.tag_name }}
-  #         release_name: ${{ env.PACKAGE_NAME }} - ${{ steps.version.outputs.release_name }}
-  #         body_path: ${{ steps.version.outputs.body_path }}
-  # deploy:
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - release
-  #   if: needs.release.outputs.update == 'true'
-  #   steps:
-  #     - uses: subosito/flutter-action@v1
-  #     - uses: actions/checkout@v2
-  #     - uses: ./.github/actions/dependency_clean
-  #       with:
-  #         package: ${{ env.PACKAGE_NAME }}
-  #     - run: flutter pub get
-  #     - name: store credentials
-  #       run: |
-  #         mkdir -p ~/.pub-cache
-  #         echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > ~/.pub-cache/credentials.json
-  #     - run: dart run tool/publish.dart --force
-  #     - name: clean up credentials
-  #       if: always()
-  #       run: shred -fzvu ~/.pub-cache/credentials.json
-  # doc:
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - release
-  #   if: needs.release.outputs.update == 'true'
-  #   steps:
-  #     - uses: subosito/flutter-action@v1
-  #     - uses: actions/checkout@v2
-  #     - uses: ./.github/actions/dependency_clean
-  #       with:
-  #         package: ${{ env.PACKAGE_NAME }}
-  #     - run: flutter pub get
-  #     - run: dartdoc --show-progress
-  #     - name: upload doc
-  #       uses: peaceiris/actions-gh-pages@v3
-  #       with:
-  #         github_token: ${{ secrets.GITHUB_TOKEN }}
-  #         publish_dir: packages/${{ env.PACKAGE_NAME }}/doc/api
-  #         commit_message: Updated documentation to v${{ needs.release.outputs.tag_name }}
-  #         destination_dir: ${{ env.PACKAGE_NAME }}
+
+  release:
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    if: github.ref == 'refs/heads/main'
+    outputs:
+      update: ${{ steps.version.outputs.update }}
+      tag_name: ${{ steps.version.outputs.tag_name }}
+    steps:
+      - uses: subosito/flutter-action@v1
+      - uses: actions/checkout@v2
+      - uses: Skycoder42/action-dart-release@v1
+        id: version
+        with:
+          src_dir: packages/${{ env.PACKAGE_NAME }}
+      - name: Create Release
+        if: steps.version.outputs.update == 'true'
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ env.PACKAGE_NAME }}/v${{ steps.version.outputs.tag_name }}
+          release_name: ${{ env.PACKAGE_NAME }} - ${{ steps.version.outputs.release_name }}
+          body_path: ${{ steps.version.outputs.body_path }}
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs:
+      - release
+    if: needs.release.outputs.update == 'true'
+    steps:
+      - uses: subosito/flutter-action@v1
+      - uses: actions/checkout@v2
+      - uses: ./.github/actions/dependency_clean
+        with:
+          package: ${{ env.PACKAGE_NAME }}
+      - name: restore prebuilt binaries (android)
+        id: cache-libsodium-bins
+        if: matrix.platform == 'android'
+        uses: actions/cache@v2
+        with:
+          path: packages/sodium_libs/android/src/main/jniLibs
+          key: libsodium-${{ matrix.platform }}-${{ hashFiles('libsodium_version.json') }}
+      - name: check cache was restored (android)
+        if: matrix.platform == 'android' && steps.cache-libsodium-bins.outputs.cache-hit != 'true'
+        run: |
+          echo 'Failed to restore android binaries from cache!'
+          exit 1
+      - run: flutter pub get
+      - name: store credentials
+        run: |
+          mkdir -p ~/.pub-cache
+          echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > ~/.pub-cache/credentials.json
+      - run: dart run tool/publish.dart --force
+      - name: clean up credentials
+        if: always()
+        run: shred -fzvu ~/.pub-cache/credentials.json
+
+  doc:
+    runs-on: ubuntu-latest
+    needs:
+      - release
+    if: needs.release.outputs.update == 'true'
+    steps:
+      - uses: subosito/flutter-action@v1
+      - uses: actions/checkout@v2
+      - uses: ./.github/actions/dependency_clean
+        with:
+          package: ${{ env.PACKAGE_NAME }}
+      - run: flutter pub get
+      - run: dartdoc --show-progress
+      - name: upload doc
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: packages/${{ env.PACKAGE_NAME }}/doc/api
+          commit_message: Updated documentation to v${{ needs.release.outputs.tag_name }}
+          destination_dir: ${{ env.PACKAGE_NAME }}
